# permissions for end users to view jobqueues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobqueue-viewer-role
rules:
- apiGroups:
  - batchjobs.example.com
  resources:
  - jobqueues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batchjobs.example.com
  resources:
  - jobqueues/status
  verbs:
  - get
